server:
  port: 8761

spring:
  application:
    name: discovery-server
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false