spring:
  redis:
    host: redis
    port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1