server:
  port: 8082

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/mac-apps/protocol/openid-connect/certs
  cloud:
    activate:
      on-profile: dev
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/api/v1/auth/**
        - id: product-service
          uri: http://product-service:9100
          predicates:
            - Path=/api/v1/product/**
      default-filters:
        - AddResponseHeader=X-Gateway-Response, Passed-through-API-Gateway
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
  redis:
    host: redis
    port: 6379