spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: dev

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always