server:
  port: 9100

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://postgres-product:5432/productdb
    username: macgyver
    password: Chr1st1@n9432
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"
