server:
  port: 8181

spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: "{cipher}2dbb4f8fb118abdff5534ba5bc8c8ed8cc1435a333a2958811a3f9713215d1ee"
    password: "{cipher}2dbb4f8fb118abdff5534ba5bc8c8ed8cc1435a333a2958811a3f9713215d1ee"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5       # Keep low to avoid exhausting local DB connections
      minimum-idle: 2            # Few idle connections are enough
      idle-timeout: 30000        # 30 sec before closing idle connections
      max-lifetime: 1800000      # 30 minutes
      connection-timeout: 10000  # 10 seconds max wait for a connection
      pool-name: DevHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.phumlani.dev/realms/ecommerce
  cache:
    type: caffeine

keycloak:
  auth-server-url: https://keycloak.phumlani.dev/
  realm: ecommerce
  resource: auth-service-client
  principle-attribute: preferred_username
  credentials:
    secret: "{cipher}98b6166452597d927dbc6eaf6111fdfd1c40aa634744493c5523528c80d71be286773c3977246e47e4e187c62b27ef7f7d4c9d3faeadef7cace5838c942cbc0a30d56b524518595646ddd8224e677e6d382b778ebcd65d423c78db676736f779d5f0b59d83ba42f64bcc2ebca066139f"

  admin:
    client-id: auth-service-admin
    client-secret: "{cipher}e060c1a48a8f924f799248a94883205713ec9d179407040c613667987a867cc9ea1c795ca045e3725cc71823849b9aa78ec92273d21aa3da1a0bd1d4e054c65bf86ebf8d1c57e900255d5fa6531fa33a5a3a62271550db40944fd15dcf35c71f73bceef063b08a7eeeecd2ddbd18d980"
  logout_uri: https://keycloak.phumlani.dev/realms/ecommerce/protocol/openid-connect/logout

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.phumlanidev.authservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO